name: deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    name: Deploy
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout web
        uses: actions/checkout@v2
        with:
          repository: 'xhofe/solid-iconify-web'
          token: ${{ secrets.MY_TOKEN }}
          path: 'web'

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Build
        run: |
          pnpm build --web
          mv packages/solid-iconify/dist/web.json ./web/src/
          cd web
          git config user.name "xhofe"
          git config user.email "i@nn.ci"
          git add .
          git commit -m "deps: update web.json for ${{ github.sha }}"

      - name: Upload dist files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          branch: main
          directory: web
          repository: xhofe/solid-iconify-web
          # force: true